### ISSUE TITLE
Missing module - `phenotrex.ml.vectorizer`

### ISSUE THREAD

**Issue by susheelbhanu** [LokiLuciferase/phenotrex#8]
Hi, 

I'm trying to predict phenotype for a MAG with the following command
```
phenotrex predict --classifier classifier/phototrophy.class \
    --min_proba 0.6 --out_explain_summary photo.expl_summary.tsv \
        --n_max_explained_features 10 --verb \
            /scratch/users/mbourquin/bins_20220215/GL_17_Down_5968.contigs.fa \
                > GL_17_Down_5968.phototrophy-pred.tsv
```

However, I'm running into this error:
```
Traceback (most recent call last):
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/bin/phenotrex", line 8, in <module>
    sys.exit(main())
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/phenotrex/cli/main.py", line 40, in main
    cli()
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/phenotrex/cli/predict.py", line 37, in predict
    _predict(*args, **kwargs)
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/phenotrex/ml/prediction.py", line 66, in predict
    model = load_classifier(filename=classifier, verb=verb)
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/phenotrex/io/serialization.py", line 47, in load_classifier
    obj = joblib.load(filename)
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/pickle.py", line 1210, in load
    dispatch[key[0]](self)
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/pickle.py", line 1526, in load_global
    klass = self.find_class(module, name)
  File "/work/projects/ensemble/tools/miniconda3/envs/phendb/lib/python3.8/pickle.py", line 1577, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'phenotrex.ml.vectorizer'
```

Could you please let me know if this can be fixed?

Thank you,
Susheel

**Comment by LokiLuciferase** [comment]
Hi Susheel,

I am assuming that you were trying to use the models published on `phendb.org/download` with the current version of `phenotrex`. 

It appears that these models were not up to date with the ones currently running in production on `phendb.org`. Thanks a lot for bringing this to my attention, I have updated the download page, and if you re-download the models, these should now work with the latest release of `phenotrex`.

all the best,
Lukas

P.S. If you don't mind, please let me know if this works now so I can close this issue.

**Comment by susheelbhanu** [comment]
Thank you @LokiLuciferase for fixing this. I have the updated classifiers and am running it on a MAG. Have a different error now:
```
[2022-04-08 11:23:02] phenotrex.io.serialization - INFO - Successfully loaded classifier (feature_type=eggNOG5-tax-2).
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:07<00:00,  7.54s/it]
Mean of empty slice.
invalid value encountered in double_scalars
```

The command I'm using is
```
phenotrex predict --classifier classifier/phototrophy.svm.class \
    --min_proba 0.6 --out_explain_summary photo.expl_summary.tsv \
        --n_max_explained_features 10 --verb \
            /scratch/users/mbourquin/bins_20220215/GL_17_Down_5968.contigs.fa \
                > GL_17_Down_5968.phototrophy-pred.tsv
```

Update: I did get the output though!!

**Comment by LokiLuciferase** [comment]
Hi again, this is a benign warning by `pandas`, and should not affect prediction accuracy. Good to hear it works now!

**Comment by susheelbhanu** [comment]
Great - thank you very much. I created #9 , but is there a way to run all the classifiers at the same time?

**Comment by LokiLuciferase** [comment]
See my comments there!
